services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./Back/.env
    restart: always

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
      args:
        - REACT_APP_EMAILJS_SERVICE_ID=${REACT_APP_EMAILJS_SERVICE_ID}
        - REACT_APP_EMAILJS_TEMPLATE_ID=${REACT_APP_EMAILJS_TEMPLATE_ID}
        - REACT_APP_EMAILJS_PUBLIC_KEY=${REACT_APP_EMAILJS_PUBLIC_KEY}
        - REACT_APP_RAZORPAY_KEY_ID=${REACT_APP_RAZORPAY_KEY_ID}
    ports:
      - "3000:80"
    env_file:
      - ./Front/.env
    depends_on:
      - backend
    restart: always
